### ISSUE TITLE
Your domain code is tightly coupled to Doctrine

### ISSUE THREAD

**Issue by usama-ahmed-bonnyprints** [dddinphp/last-wishes#15]
https://github.com/dddinphp/last-wishes/blob/master/src/Lw/Domain/Model/User/User.php#L7

You are using doctrine collections inside Domain code, shouldn't that be done inside infrastructure.

**Comment by theUniC** [comment]
Hi,

Thanks to open an issue. I kindly disagree. This code is coupled to the Doctrine Collections (not whole Doctrine) library. A library that provides an abstraction around collections. Mainly for two reasons:
- Doctrine Collections provide what we consider a language feature that actually isn't implemented on PHP.
- In order to provide lazy loading to related entities when building aggregates.

It could be done on the infrastructure side as you point out, but the downside is that the design gets much more complex. Coupling to the doctrine collections library is perfectly fine as it doesn't mix different concerns.

**Comment by usama-ahmed-bonnyprints** [comment]
Doctrine Collection comes with an extra set of functions which are not used anywhere inside the code. You could always replace

`$this->wishes = new ArrayCollection();`
with
`$this->wishes = []`

everything will work and `use Doctrine\Common\Collections\Criteria` can also be removed since not used inside the code.

**Comment by theUniC** [comment]
Yup! We already know! Thanks again to point it out! But this is not the recommended way to deal with one-to-many and many-to-many relationships when using Doctrine. You can read it here

**http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#collections**

**http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/best-practices.html#initialize-collections-in-the-constructor**

Thanks!
